version: "3"
services:
  phoenix_container:
    restart: unless-stopped
    depends_on:
      postgres-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile-dev
    deploy:
      mode: replicated
      replicas: 5
    environment:
      SECRET_KEY_BASE: 7HWxPLzpxwFyzAcybYwV1dZDQoXH1XvP8sd16vEG4GDajOJ4OJ/l0XoH0lOXW0oc
      PHX_HOST: localhost
      PORT: 5000
    env_file:
      - ./docker-local/dev.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - phoenix_container
    ports:
      - 4000:4000

  postgres-db:
    restart: unless-stopped
    volumes:
      - ./docker-local/data:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/:ro
    image: postgres:14.6-bullseye
    env_file:
      - ./docker-local/db.env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 10s
      timeout: 45s
      retries: 10
      start_period: 30s